---

#
# Role-speciifc configuration
#

# Role:
#   name: `ansible-community.ansible-nomad`
#   source: https://github.com/ansible-community/ansible-nomad`

# Specifies the amount of memory to reserve, in MB.
target_nomad_reserved_memory: 300

# Specifies the amount of disk to reserve, in MB.
target_nomad_reserved_disk: 1500

# Specifies the amount of CPU to reserve, in MHz.
target_nomad_reserved_cpu: 300

# The Consul Master key/token to be used to configure ACLs for the cluster.
consul_master_key: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

# The Vault token, with access to the kv-v1 store, to be used to store
# Consul ACLs.
vault_master_token: "s.xxxxxxxxxxxxxxxxxxxxx"

# A `target_`-namespaced variable (to avoid conflicts), with the value of the
# primary vault datacenter, for access via Consul-configured DNS.
target_vault_primary_datacenter: global